receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:9464"

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

processors:
  batch:
  resource:
    attributes:
      - key: service.name
        from_attribute: service.name
        action: upsert

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp]
      exporters: [debug]