server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: job
        replacement: 'docker_logs'

      - source_labels: [ '__meta_docker_container_name' ]
        target_label: 'container_name'
        regex: '/(.*)'

      - source_labels: [ '__meta_docker_container_label_com_docker_compose_service' ]
        target_label: service

      - source_labels: [ 'container_name' ]
        regex: 'promtail'
        action: drop

    pipeline_stages:
      - docker: {}

      - json:
          expressions:
            level: level
            logger: logger
            message: message
            trace_id: trace_id
            span_id: span_id
            request_id: request_id

      - labels:
          job:
          level:
          trace_id:
          span_id:
