server:
  http_listen_port: 3200 # Le port que Grafana utilisera
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          # Tempo écoutera les traces OTLP/gRPC venant du Collector
          endpoint: 0.0.0.0:4317

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks